services:
  - docker
language: node_js
cache:
  directories:
    - node_modules
    - kits/beta-base/node_modules
    - kits/democracy/node_modules
    - kits/multisig/node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  - TASK=lint
  - TASK=test:beta-base
  - TASK=test:democracy
  - TASK=test:multisig
  - TASK=test:trust
  - TASK=test:agp1
matrix:
  allow_failures:
    - env: TASK=test:agp1
  fast_finish: true
install:
  - travis_wait 20 npm install
script:
  - travis_wait 60 npm run $TASK
