version: "2"
services:
  devnet:
    image: aragon/geth-devnet
    volumes:
      - ${ETHDATA_LOCAL_PATH}:/root/.ethdata
    ports:
      - "8535:8545"
      - "8546:8546"
    expose:
      - 8545
    environment:
      - NETWORK_ID=16
      - DEV_CHAIN_ENABLED=true
    networks:
      - devnet
  ipfs:
    image: aragon/ipfs
    ports:
      - "5001:5001"
      - "4001:4001"
    expose:
      - 5001
    networks:
      - ipfs
networks:
  devnet:
  ipfs:
